name: Update Counter

on:
  schedule:
    # Run every day at midnight UTC
    - cron: "0 0 * * *"

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Update the counter using a script
      - name: Update counter
        run: |
          COUNTER_FILE="counter.txt"

          if [ -f "$COUNTER_FILE" ]; then
            CURRENT_COUNT=$(grep -o '[0-9]*$' "$COUNTER_FILE")
            if [ -z "$CURRENT_COUNT" ]; then
              CURRENT_COUNT=0
            fi
          else
            CURRENT_COUNT=0
          fi

          NEW_COUNT=$((CURRENT_COUNT + 1))

          echo "$NEW_COUNT" > "$COUNTER_FILE"

      # Commit and push changes
      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add counter.txt
          git commit -m "Update counter to $NEW_COUNT"
          git push
